cc_test(
    name = "config_test",
    srcs = ["config_test.cc"],
    deps = [
        "//wasm/utility:config",
        "@gtest//:gtest",
        "@gtest//:gtest_main"
    ],
)

cc_test(
    name = "http_parser_test",
    srcs = ["http_parser_test.cc"],
    deps = [
        "//wasm/utility:http_parser",
        "@gtest//:gtest",
        "@gtest//:gtest_main"
    ]
)

cc_test(
    name = "sqli_test",
    srcs = ["sqli_test.cc"],
    deps = [
        "//wasm/utility:sqli",
        "@gtest//:gtest",
        "@gtest//:gtest_main"
    ]
)
